version = 0.1

[default.deploy.parameters]
stack_name = "sun-phase-web"
resolve_s3 = true
s3_prefix = "sun-phase-web"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
