version = 0.1

[default.deploy.parameters]
stack_name = "gis-service-search-web"
region = "us-east-2"
resolve_s3 = true
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
